# Generated by Django 3.2.18 on 2023-06-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rfc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RFC'),
        ),
    ]
