# Generated by Django 3.2.18 on 2023-06-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='nombre'),
        ),
    ]
